triptie/tripapp/urls.py
from django.urls import path
from . import views

app_name = 'tripapp'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path('edit_profile/<username>/', views.EditProfileView.as_view(), name='edit_profile'),
    path('my_trip_plans/<username>/', views.MyTripPlansView.as_view(), name='my_trip_plans'),
    path('my_likes/<username>/', views.MyLikesView.as_view(), name='my_likes'),
    path('add_plan/<username>', views.AddPlan.as_view(), name='add_plan'),
    path('success/',views.SuccessView.as_view(), name='success'),
    path('trip_plan_search/', views.TripPlanSearch.as_view(), name='trip_plan_search'),
    path('add_commnent/', views.AddComment.as_view(), name='add_comment'),
    path('add_like/', views.AddLike.as_view(), name='add_like'),
    path('explore/', views.explore, name='explore'),
    path('search_youtube/', views.search_youtube_for_city, name='search_youtube'),
    path('weather/', views.WeatherView.as_view(), name='weather'),
    path('search_youtube/', views.search_youtube_for_city, name='search_youtube'),
]

triptie/triptie/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from tripapp import views  # Ensure you have home and explore_view defined here

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view(), name='index'),  # Homepage handled by IndexView
    path('tripapp/', include('tripapp.urls')),
    path('accounts/', include('registration.backends.simple.urls')),
    path('home/', views.home, name='home'),  # Path for the homepage view if different from IndexView
    path('weather/', views.WeatherView.as_view, name='weather'),  # Path for the homepage view if different from IndexView

    path('explore/', views.explore_view, name='explore'),  # Path for the explore view
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

triptie/tripapp/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models


class UserProfile(models.Model):
    Gender_Choices = [
        ('M', 'Male'),
        ('F', 'Female'),
        ('O', 'Other'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    gender = models.CharField(max_length=1, choices=Gender_Choices, blank=True)
    age = models.PositiveIntegerField(null=True, blank=True)
    bio = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


# table for posting a trip on the app

class TripPlan(models.Model):
    TITLE_MAX_VALUE = 128
    CITY_MAX_VALUE = 32
    DESCRIPTION_MAX_VALUE = 512
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=TITLE_MAX_VALUE)
    description = models.TextField(max_length=DESCRIPTION_MAX_VALUE)
    destination_city = models.CharField(max_length=CITY_MAX_VALUE)
    start_date = models.DateField()
    end_date = models.DateField()
    is_private = models.BooleanField(default=False,blank=True)
    image = models.ImageField(upload_to='trip_images')

    def clean(self):
        # Ensure end_date is after start_date
        if self.end_date < self.start_date:
            raise ValidationError('End date must be after start date.')


# table of giving likes to the post

class LikePost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    trip_plan = models.ForeignKey(TripPlan, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)


# table for commenting on the post
class Comment(models.Model):
    COMMENT_MAX_VALUE = 128
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    trip_plan = models.ForeignKey(TripPlan, on_delete=models.CASCADE)
    comment_content = models.CharField(max_length=COMMENT_MAX_VALUE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_at']

triptie/tripapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.http import JsonResponse
from django.views.generic import TemplateView

from .explorePage import search_youtube_for_city
import requests
from tripapp.form import UserProfileForm, TripPlanForm, TripPlanSearchForm
from tripapp.models import UserProfile, TripPlan, LikePost
from tripapp.form import UserProfileForm, TripPlanForm
from tripapp.models import UserProfile, TripPlan, LikePost


class IndexView(View):
    def get(self, request):
        return render(request, 'tripapp/index.html')


# API key
YOUTUBE_API_KEY = 'AIzaSyDbSCu3VjTPVTS89Nz0K-fK7Jn4SLcUc1o'


def explore(request):
    return render(request, 'tripapp/explore.html')


def home(request):
    return render(request, 'tripapp/home.html')


class AboutView(View):
    def get(self, request):
        return render(request, 'tripapp/about.html')


def index(request):
    return render(request, 'tripapp/index.html')


class ProfileView(View):
    def get_user_details(self, username):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return None

        user_profile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({'gender': user_profile.gender,
                                'picture': user_profile.picture,
                                'bio': user_profile.bio, })

        return user, user_profile, form

    @method_decorator(login_required)
    def get(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('tripapp:index'))

        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}

        return render(request, 'tripapp/profile.html', context_dict)


class EditProfileView(View):

    @method_decorator(login_required)
    def get(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('tripapp:index'))

        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}

        return render(request, 'tripapp/edit_profile.html', context_dict)

    def get_user_details(self, username):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return None

        user_profile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({'gender': user_profile.gender,
                                'picture': user_profile.picture,
                                'bio': user_profile.bio, })

        return user, user_profile, form

    @method_decorator(login_required)
    def post(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('tripapp:index'))

        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)

        if form.is_valid():
            form.save(commit=True)
            return redirect(reverse('tripapp:profile',
                                    kwargs={'username': username}))
        else:
            print(form.errors)

        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}

        return render(request, 'tripapp/edit_profile.html', context_dict)


class MyTripPlansView(View):
    @method_decorator(login_required)
    def get(self, request, username):
        trip_plans = TripPlan.objects.filter(user=request.user).order_by('-start_date')

        return render(request, 'tripapp/my_trip_plans.html', {'trip_plans': trip_plans})


class MyLikesView(View):
    @method_decorator(login_required)
    def get(self, request, username):
        liked_trip_plans = LikePost.objects.filter(user=request.user).select_related('trip_plan')

        # Extract the trip plans from the likes
        trip_plans = [like.trip_plan for like in liked_trip_plans]

        context = {
            'trip_plans': trip_plans,
            'user': request.user,
        }

        return render(request, 'tripapp/my_likes.html', context)


class AddPlan(View):
    @method_decorator(login_required)
    def post(self, request, username):
        form = TripPlanForm(request.POST, request.FILES)
        context = {
            'username': username,
        }
        if form.is_valid():
            trip_plan = form.save(commit=False)
            trip_plan.user = request.user
            trip_plan.save()
            return render(request, 'tripapp/success.html')

        context = {
            'form': form,
            'username': username,
        }
        return render(request, 'tripapp/add_plan.html', context)

    @method_decorator(login_required)
    def get(self, request, username):
        context = {
            'username': username,
        }
        return render(request, 'tripapp/add_plan.html', context)


class TripPlanSearch(View):
    @method_decorator(login_required)
    def get(self, request):
        form = TripPlanSearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # Exclude private trip plans
            trip_plans = TripPlan.objects.filter(title__icontains=query, is_private=False)
            liked_trip_plans = []
            user = request.user
            for trip_plan in trip_plans:
                liked = LikePost.objects.filter(user=user, trip_plan=trip_plan).exists()
                liked_trip_plans.append({'trip_plan': trip_plan, 'liked': liked})
            return render(request, 'tripapp/trip_plan_search.html', {'trip_plans': liked_trip_plans, 'query': query})

        return render(request, 'tripapp/trip_plan_search.html', {'form': form})


class SuccessView(View):
    @method_decorator(login_required)
    def get(self, request):
        return render(request, 'tripapp/success.html')


class AddComment(View):
    @method_decorator(login_required)
    def post(self, request, username):
        return


class AddLike(View):
    @method_decorator(login_required)
    def get(self, request, trip_plan_id):
        trip_plan = TripPlan.objects.get(id=trip_plan_id)
        user = request.user

        # Check if the user has already liked the trip plan
        if LikePost.objects.filter(user=user, trip_plan=trip_plan).exists():
            # User has already liked the trip plan, return an error response
            return JsonResponse({'error': 'User has already liked this trip plan'}, status=400)

        # Like the trip plan
        LikePost.objects.create(user=user, trip_plan=trip_plan)
        return JsonResponse({'success': 'Trip plan liked successfully'})


def user_has_liked_trip_plan(user, trip_plan_id):
    return LikePost.objects.filter(user=user, trip_plan_id=trip_plan_id).exists()


def weather(request):
    return render(request, 'tripapp/weather.html')
class WeatherView(View):
    def get(self, request):
        return render(request, 'tripapp/weather.html')


def myposts(request):
    return render(request, 'tripapp/myposts.html')


def messages(request):
    return render(request, 'tripapp/messages.html')


def explore_view(request):
    return render(request, 'tripapp/explore.html')


def explore(request):
    return render(request, 'tripapp/explore.html')


# def search_youtube(request):
# city_name = 'New York'
def search_youtube_for_city(request):
    city_name = request.GET.get('city', 'New York')

    search_url = 'https://www.googleapis.com/youtube/v3/search'
    params = {
        'part': 'snippet',
        'q': city_name,
        'type': 'video',
        'key': YOUTUBE_API_KEY,
        'maxResults': 5
    }
    response = requests.get(search_url, params=params)
    videos = response.json().get('items', [])
    return JsonResponse(videos, safe=False)

triptie/templates/tripapp/about.html
{% extends 'tripapp/base.html' %}
{% load static %}

{% block title_block %}
    Add a Plan
{% endblock %}

{% block body_block %}
    <p>This is about page</p>
{% endblock %}

triptie/templates/tripapp/add_plan.html
{% extends 'tripapp/base.html' %}
{% load static %}

{% block title_Block %}
    Add a Plan
{% endblock %}

{% block body_block %}
    <div class="centered-form">
        <div class="form-container">
            <div class="card">
                <h5 class="card-header text-center">Add a New Trip Plan</h5>
                <div class="card-body">
                    <form action="{% url 'tripapp:add_plan' username %}" method="post" enctype="multipart/form-data">
                        <div class="mb-3">
                            <label for="title" class="form-label">Title</label>
                            <input type="text" class="form-control" id="title" name="title"
                                   placeholder="Title of your trip plan" required>
                        </div>
                        <div class="mb-3">
                            <label for="description" class="form-label">Description</label>
                            <textarea class="form-control" id="description" name="description" rows="3"
                                      required></textarea>
                        </div>
                        <div class="mb-3">
                            <label for="destination_city" class="form-label">Destination City</label>
                            <input type="text" class="form-control" id="destination_city" name="destination_city"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="start_date" class="form-label">Start Date</label>
                            <input type="date" class="form-control" id="start_date" name="start_date" required>
                        </div>
                        <div class="mb-3">
                            <label for="end_date" class="form-label">End Date</label>
                            <input type="date" class="form-control" id="end_date" name="end_date" required>
                        </div>
                        <div class="mb-3 form-check">
                            <input type="checkbox" class="form-check-input" id="is_private" name="is_private">
                            <label class="form-check-label" for="is_private">Make this trip private</label>
                        </div>
                        <div class="mb-3">
                            <label for="image" class="form-label">Trip Image</label>
                            <input class="form-control" type="file" id="image" name="image" accept="image/*">
                        </div>
                        <button type="submit" value="submit" class="btn btn-primary">Submit</button>
                    </form>

                    {% if form.errors %}
                        <div class="alert alert-danger">
                            <strong>Error!</strong> Please correct the following errors:
                            <ul>
                                {% for field, errors in form.errors.items %}
                                    {% for error in errors %}
                                        <li>{{ field|title }}: {{ error }}</li>
                                    {% endfor %}
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}

triptie/templates/tripapp/base.html
<!DOCTYPE html>
{% load static %}
{% load tripapp_template_tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <title>{% block title_block %}Document{% endblock %}</title>
</head>

<body>
    <section class="showcase">
        <header style="display: flex; justify-content: space-between; align-items: center;">
            <h2 class="logo">TripTie</h2>
            <div class="toggle" style="margin-left: auto;"></div>
        </header>
        
        <div class="content">
            {% block body_block %}
            {% endblock %}
        </div>
    </section>

    <div class="menu">
        <ul>
            <li><a href="{% url 'tripapp:index' %}">Home</a></li>
            <!-- Other menu items -->
        </ul>
    </div>

    <script src="{% static 'js/index.js' %}"></script>
    <script src="{% static 'js/base-ajax.js' %}"></script>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>
</body>
</html>

triptie/templates/tripapp/edit_profile.html
{% extends 'tripapp/base.html' %}
{% load static %}

{% block title_Block %}
    {user.username} Edit Profile
{% endblock %}

{% block body_block %}
    <div class="container">
        <div class="row">
            {% if user_profile.picture %}
                <img src="{{ MEDIA_URL }}{{ user_profile.picture.url }}" width="300" height="300"
                     alt="{{ selected_user.username }}'s profile image"/>
            {% else %}
                <img src="https://lorempixel.com/300/300/people/" width="300" height="300" alt="Placeholder image"/>
            {% endif %}
            <br/>
            <div>
                {% if user == user %}
                    <form method="post" action="." enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Update"/>
                    </form>

                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

triptie/templates/tripapp/explore.html
{% extends 'tripapp/base.html' %}
{% load static %}
{% block title_block %}
Add a Plan
{% endblock %}

{% block body_block %}
<main class="showcase">
    <div class="overlay"></div>
    <div class="content">
        <h2>Welcome to the Explore Page!</h2>
        <form id="search-form" class="text">
            <input type="text" id="city-name" placeholder="Enter a city name" class="form-control">
            <button type="submit" class="btn btn-primary mt-3">Search</button>
        </form>
        <div id="youtube-videos" class="mt-5">
            <div id="london-video" class="city-video"></div>
            <div id="paris-video" class="city-video"></div>
            <div id="edinburgh-video" class="city-video"></div>
        </div>
    </div>
</main>
<script src="{% static 'js/explore.js' %}"></script>
{% endblock %}

triptie/templates/tripapp/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/index.js' %}"></script>
    <title>About Page</title>
</head>
<body>
    <header>
        <h1>About Triptie</h1>
    </header>
    <nav>
        <ul>
            <li><a href="{% url 'index' %}">Homef</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
        </ul>
    </nav>
    <main>
        <h2>About Page</h2>
        <p>This is the home page of the Triptie website.</p>
    </main>
</body>
</html>

triptie/templates/tripapp/index.html
{% load static %}
{% load tripapp_template_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <link rel="stylesheet" href="{% static 'css/index.css' %}">

  <title>Document</title>
</head>
<body>
  <section class="showcase">
    <header>
      <h2 class="logo">TripTie</h2>
      <div class="toggle"></div>
    </header>
    <video src="{% static 'media/video.mp4' %}" muted loop autoplay></video>
    <div class="overlay"></div>
    <div class="text">
      <h2>Never Stop </h2>
      <h3>Exploring The World</h3>

      <p>Welcome to TripTie, your ultimate destination for unforgettable travel experiences! Whether you're dreaming of relaxing on pristine beaches, exploring vibrant cities, or embarking on thrilling adventures, you can find your right spot.
        Discover a world of possibilities and find your travel buddy.
        Browse our travel guides and articles for insider tips, hidden gems, and must-see attractions in each destination.</p>
         <a href="{% url 'tripapp:explore' %}">Explore</a>
    </div>
    <ul class="social">
      <li><a href="#"><img src="https://i.ibb.co/x7P24fL/facebook.png" onclick="shareOnFacebook()"></a></li>
      <li><a href="#"><img src="https://i.ibb.co/Wnxq2Nq/twitter.png" onclick="tweetShare()"></a></li>
      <li><a href="#"><img src="https://i.ibb.co/ySwtH4B/instagram.png"></a></li>
    </ul>
  </section>
  <div class="menu">
    <ul>
      <li><a href="{% url 'tripapp:index' %}">Home</a></li>
{#      <li><a href="{% url 'tripapp:profile' %}">Profile</a></li> #}
  <li><a id="loginRegisterButton" href="{% url 'auth_login' %}">Login | Register</a></li> 
      <li><a href="{% url 'tripapp:about' %}">About</a></li>
    </ul>
  </div>
<script src="{% static 'js/index.js' %}"></script>
<script>
  function tweetShare() {
    window.open('https://twitter.com/intent/tweet?text=Check%20out%20this%20awesome%20website%21%20https%3A%2F%2Fexample.com%2F');
  }

  function shareOnFacebook() {
      var url = encodeURIComponent(window.location.href);
      window.open('https://www.facebook.com/sharer/sharer.php?u=' + url, '_blank');
  }
</script>
</body>
</html>

triptie/templates/tripapp/my_likes.html
{% extends 'tripapp/base.html' %}
{% load static %}

{% block title_Block %}
    Trip Plans I Liked
{% endblock %}

{% block body_block %}
    <div class="container mt-4">
        <h1>My Liked Trip Plans</h1>
        <hr>
        {% if trip_plans %}
            <div class="d-flex flex-column align-items-center">
                {% for trip_plan in trip_plans %}
                    <div class="card mb-4" style="width: 100%; max-width: 600px;">
                        {% if trip_plan.image %}
                            <img src="{{ trip_plan.image.url }}" class="card-img-top" alt="{{ trip_plan.title }}">
                        {% else %}
                            <img src="https://i.ibb.co/FKrsX1r/hot-air-balloon-4095513-1280.jpg" class="card-img-top" alt="Default Image">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ trip_plan.title }}</h5>
                            <p class="card-text">{{ trip_plan.description }}</p>
                        </div>
                        <div class="card-footer">
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">Trip to {{ trip_plan.destination_city }}</small>
                                <small class="text-muted">{{ trip_plan.start_date }} - {{ trip_plan.end_date }}</small>
                            </div>
                            <div class="d-flex justify-content-between align-items-center mt-2">
                                <a href="#" class="btn btn-outline-primary btn-sm">Like</a>
                                <a href="#" class="btn btn-outline-secondary btn-sm">Comment</a>
                                <a href="{% url 'tripapp:trip_detail' trip_plan.id %}"
                                   class="btn btn-outline-info btn-sm">Details</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>You have not liked any trip plans yet.</p>
        {% endif %}
    </div>


{% endblock %}

triptie/templates/tripapp/my_trip_plans.html
{% extends 'tripapp/base.html' %}
{% load static %}

{% block title_Block %}
    {{ user.username }}'s Trip Plans
{% endblock %}

{% block body_block %}
    <div class="container mt-4">
    <h1>My Trip Plans</h1>
    <hr>
    {% if trip_plans %}
        <div class="d-flex flex-column align-items-center">
            {% for trip_plan in trip_plans %}
                <div class="card mb-4" style="width: 100%; max-width: 600px;">
                    {% if trip_plan.image %}
                        <img src="{{ MEDIA_URL }}{{ trip_plan.image.url }}" class="card-img-top" alt="{{ trip_plan.title }}">
                    {% else %}
                        <img src="https://i.ibb.co/FKrsX1r/hot-air-balloon-4095513-1280.jpg" class="card-img-top" alt="Default Image">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ trip_plan.title }}</h5>
                        <p class="card-text">{{ trip_plan.description }}</p>
                    </div>
                    <div class="card-footer">
                        <div class="d-flex justify-content-between align-items-center">
                            <small class="text-muted">Trip to {{ trip_plan.destination_city }}</small>
                            <small class="text-muted">{{ trip_plan.start_date }} - {{ trip_plan.end_date }}</small>
                        </div>
                        <div class="d-flex justify-content-between align-items-center mt-2">
                            <a href="#" class="btn btn-outline-primary btn-sm">Like</a>
                            <a href="#" class="btn btn-outline-secondary btn-sm">Comment</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <p>You have not liked any trip plans yet.</p>
    {% endif %}
</div>
    
    
{% endblock %}

triptie/templates/tripapp/profile.html
{% extends 'tripapp/base.html' %}
{% load static %}

{% block title_Block %}
    Profile for {{ selected_user.username }}
{% endblock %}

{% block body_block %}
    <div class="container">
        <div class="row">
            {% if user_profile.picture %}
                <img src="{{ MEDIA_URL }}{{ user_profile.picture.url }}" width="300" height="300"
                     alt="{{ selected_user.username }}'s profile image"/>
            {% else %}
                <img src="https://ibb.co/xm1C47n" width="300" height="300" alt="Placeholder image"/>
            {% endif %}
            <br/>
            <div>
                <p>
                    <strong>Username:</strong> {{ user_profile.user.username }}<br>
                    <strong>Gender:</strong> {{ user_profile.gender }}<br>
                    <strong>Age:</strong> {{ user_profile.age }}<br>
                    <strong>Bio:</strong> {{ user_profile.bio }}<br>
                </p>
                {% if selected_user == user %}
                    <a href="{% url 'tripapp:edit_profile' username=user.username %}" class="btn btn-primary">Edit Profile</a>
                    <a href="{% url 'tripapp:my_trip_plans' username=user.username %}" class="btn btn-secondary">My Trip Plan</a>
                    <a href="{% url 'tripapp:my_likes' username=user.username %}" class="btn btn-info">My Likes</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

triptie/templates/tripapp/success.html
{% extends 'tripapp/base.html' %}
{% load static %}

{% block title_Block %}
    Success
{% endblock %}

{% block body_block %}
    <h1>Congratulations! You add a plan successfully!</h1>

    <a href="{% url 'tripapp:my_trip_plans' user.username %}" class="btn btn-primary">View My Trip Plans</a>
{% endblock %}

triptie/templates/tripapp/trip_plan_search.html
{% extends 'tripapp/base.html' %}
{% load static %}

{% block title_Block %}
    Search For Plan
{% endblock %}

{% block body_block %}
    <form method="GET" action="{% url 'tripapp:trip_plan_search' %}">
        {{ form.query }}
        <button class="btn btn-primary" type="submit">Search</button>
    </form>

    <div class="container mt-4">
    {% if trip_plans %}
        <h2>Search Results for "{{ query }}"</h2>
        <hr>
        {% if liked_trip_plans %}
            <div class="d-flex flex-column align-items-center">
                {% for trip_plan in trip_plans %}
                    <div class="card mb-4" style="width: 100%; max-width: 600px;">
                        {% if liked_trip_plan.image %}
                            <img src="{{ MEDIA_URL }}{{ trip_plan.image.url }}" class="card-img-top"
                                 alt="{{ trip_plan.title }}">
                        {% else %}
                            <img src="https://i.ibb.co/FKrsX1r/hot-air-balloon-4095513-1280.jpg" class="card-img-top"
                                 alt="Default Image">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ liked_trip_plan.title }}</h5>
                            <p class="card-text">{{ liked_trip_plan.description }}</p>
                        </div>
                        <div class="card-footer">
                            <div class="d-flex justify-content-between align-items-center">
                                <small class="text-muted">Trip to {{ liked_trip_plan.destination_city }}</small>
                                <small class="text-muted">{{ liked_trip_plan.start_date }}
                                    - {{ liked_trip_plan.end_date }}</small>
                            </div>
                            <div class="d-flex justify-content-between align-items-center mt-2">
                                {% if liked_trip_plan.liked %}
                                    <button class="btn btn-outline-primary btn-sm like-btn liked"
                                            data-trip-plan-id="{{ liked_trip_plan.trip_plan.id }}">Like
                                    </button>
                                {% else %}
                                    <button class="btn btn-outline-primary btn-sm like-btn"
                                            data-trip-plan-id="{{ liked_trip_plan.trip_plan.id }}">Like
                                    </button>
                                {% endif %}
                                <a href="#" class="btn btn-outline-secondary btn-sm">Comment</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>No results found for "{{ query }}".</p>
        {% endif %}
    {% endif %}
{% endblock %}